### ISSUE TITLE
Add multi line support in app names

### ISSUE THREAD

**Issue by rago666** [adhec/dittoMenuKDE#1]
![Screenshot_20210629_163657](https://user-images.githubusercontent.com/51720144/123783656-6c931680-d8f8-11eb-87b2-d4ee49359dce.png)

Similar to default application launcher 
![Screenshot_20210629_163951](https://user-images.githubusercontent.com/51720144/123783954-bd0a7400-d8f8-11eb-8b35-f03c891bd73b.png)

**Comment by adhec** [comment]
thanks for the feedback, option added in [commit](https://github.com/adhec/dittoMenuKDE/commit/f551425265d6ac0e0cd0fe75859c091481369580)

![image](https://user-images.githubusercontent.com/1858005/124366226-bbe88800-dc13-11eb-8157-8f5022c55c3b.png)
