### ISSUE TITLE
Ditto Menu not loading

### ISSUE THREAD

**Issue by silvolde428** [adhec/dittoMenuKDE#22]
Having this error when I try to open ditto menu. Can someone tell me how to fix it?

file:///home/silvolde/.local/share/plasma/plasmoids/org.kde.plasma.dittomenu/contents/ui/main.qml:59:9: Type MenuRepresentation unavailable

file:///home/silvolde/.local/share/plasma/plasmoids/org.kde.plasma.dittomenu/contents/ui/MenuRepresentation.qml:37:1: module "org.kde.plasma.private.quicklaunch" is not installed

My distro is Endeavour OS with KDE if that helps any

**Comment by apandada1** [comment]
The solution is to install `kdeplasma-addons` with `sudo pacman -S kdeplasma-addons`

**Comment by adhec** [comment]
Updated dependencies in readme.md. Thanks
