### ISSUE TITLE
BUG in the case of "the program start button is centered"

### ISSUE THREAD

**Issue by ghost** [adhec/dittoMenuKDE#24]
KDE PLASMA version: 5.24.6
It's a beautiful launcher, but unfortunately has a problem.

When I put the "Program Launcher" in the middle position, and then open the ditto menu. As shown in the picture, I will find that it cannot be centered.

### For example 😭
![Screenshot_20220911_205845](https://user-images.githubusercontent.com/106905547/189529028-5755d7d5-59e7-4d8b-b7ec-97f661e23f82.png)

**Comment by adhec** [comment]
Hi @Trapshell , you tried to modify the launcher position in the widget settings.
