### ISSUE TITLE
Moving items around in the favorites is slow and buggy

### ISSUE THREAD

**Issue by niobium93** [adhec/dittoMenuKDE#26]
Trying to move an item in the favorites to a different position is sometimes very slow. Have to wait a few seconds after dragging the mouse for the item to actually move. 

Furthermore, after you move an item, clicking anywhere on the menu just closes the whole menu. Have to reopen the menu to do anything else. Makes it VERY annoying to move multiple favorites around and set it up in the order you want.

**Comment by adhec** [comment]
Fixed since ubuntu jammy updates.
