### ISSUE TITLE
Can't add/remove applications from favorites

### ISSUE THREAD

**Issue by Setherz6104** [adhec/dittoMenuKDE#7]
Just installed Ditto and I LOVE it. It was working great for a while, then all of the sudden I can't edit my favorites. If I right-click an application in my favorites and try to remove it, it does nothing. Same for if I'm trying to add an application to my favorites.

![image](https://user-images.githubusercontent.com/25572885/141018974-c8a1752e-8ba1-4550-be52-66d1cc5b4ea8.png)

Ditto Menu Version: 1.0
OS: Kubuntu 21.10
KDE Plasma Version: 5.23.2

**Comment by Herreramartos** [comment]
same in Arch btw ;D

**Comment by linksilva** [comment]
Really nice application menu but also having this issue. Won't update the favorites page.
